### ISSUE TITLE
Grouped GridPanel's grouping summary not working with Count summary type

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#692]
First part of this forum thread: http://forums.ext.net/showthread.php?50911 (until 5th post).

`Ext.grid.feature.AbstractSummary` has a `getSummary` method that was returning an invalid property for the _count_ summary type.

This is related to #682, issue entry 51.

**Comment by fabriciomurta** [comment]
The fix apparently did not work with the example `GridPanel/Miscellaneous/Grouping_TotalRow`

**Comment by fabriciomurta** [comment]
Fixed in revision `6323` (trunk). It goes to `3.1.0`.

**Comment by DaniilVeriga** [comment]
Changed the initial fix in the revision 6474 (trunk) to get #809, entry 26/91 fixed as well.

**Comment by DaniilVeriga** [comment]
The issue is still reproducible with ExtJS 6.0.1. So, our fix is still there.
